### ISSUE TITLE
Version 0.1 Checklist

### ISSUE THREAD

**Issue by CD1212** [CD1212/Doughnut#2]
- [ ] Trim episode title
- [ ] Auto close podcast subscribe sheet
- [ ] Improve library opening, creating mechanism
- [ ] Remove HTML chars from plain text episode description
