### ISSUE TITLE
Version 0.2 Checklist

### ISSUE THREAD

**Issue by CD1212** [CD1212/Doughnut#3]
- [x] App icon number of unplayed episodes
- [x] Notification on discovery of new episodes
- [ ] Show media file ID3 artwork if available and downloaded, fallback to podcast artwork
- [ ] Ability to create a podcast without a feed
- [ ] Ability to delete episode
- [ ] Ability to show deleted episodes
